version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: api
    ports:
      - "80:5000"
    restart: always
    # volumes:
    #   - .:/usr/src/app

    
